# Generated by Django 5.0 on 2025-11-21 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                ("content", models.TextField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="published",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["-created_on"],
            },
        ),
        migrations.AddField(
            model_name="enquiry",
            name="category",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("meta_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("meta_keywords", models.TextField(blank=True, null=True)),
                (
                    "spec1heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spec1answer", models.TextField(blank=True, null=True)),
                (
                    "spec2heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spec2answer", models.TextField(blank=True, null=True)),
                (
                    "spec3heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spec3answer", models.TextField(blank=True, null=True)),
                (
                    "spec4heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spec4answer", models.TextField(blank=True, null=True)),
                (
                    "spec5heading",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spec5answer", models.TextField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="dash.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
